NAME:=		SOIL
SRCS:=		$(shell find . -maxdepth 1 -name '*.c')
OBJS:=		${SRCS:.c=.o}
BIN:=		lib${NAME}.a
LDBIN:=		lib${NAME}.dynlib

CFLAGS=		-O2 -I. -Wall
LDFLAGS=	-framework OpenGL -framework CoreFoundation

all: ${BIN} ${LDBIN}

${BIN}: ${OBJS}
	ar r $@ $^
	ranlib $@

${LDBIN}: ${OBJS}
	${CC} ${CFLAGS} ${LDFLAGS} -shared -o $@ $^

.PHONY: clean
clean:
	rm -f ${OBJS} ${BIN} ${LDBIN}
